services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    volumes:
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  elasticdata: